### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by nwithan8** [TBosak/mkfd#2]
Please consider Dockerizing this and releasing a prebuilt image to Docker Hub or GitHub Container Registry

**Comment by TBosak** [comment]
Done!
https://hub.docker.com/r/tbosk/mkfd

**Comment by TBosak** [comment]
Awesome, thanks for the support. I'm not sure what these templates entail, but you may need to update it, as I had readme instructions mapping to the wrong path. 😭

**Comment by nwithan8** [comment]
> Awesome, thanks for the support. I'm not sure what these templates entail, but you may need to update it, as I had readme instructions mapping to the wrong path. 😭

Yep, noticed that during testing and accounted for it
