### ISSUE TITLE
Internal Server Error on docker container

### ISSUE THREAD

**Issue by dhanadhan** [TBosak/mkfd#3]
I successfully deployed this app using the docker stack shown below. It is running, but I am unable to access it via localhost:5000 as it gives "Internal Server Error". Am I doing it right?

Container logs shows:

> cp: cannot stat '/backup-configs/*': No such file or directory
> ENOENT: No such file or directory
>    errno: -2
>  syscall: "open"
>    path: "./public/index.html"

Docker stack:

> version: '3.9'
> services:
>   mkfd:
>     image: tbosk/mkfd:latest
>     container_name: mkfd
>     environment:
>         - COOKIE_SECRET=some key
>         - PASSKEY=some key
>     volumes:
>         - ./:/public
>     ports:
>         - 5000:5000

**Comment by TBosak** [comment]
Sorry, I forgot to update the readme, map to /configs instead of /public. Let me know if you're still having issues after.

**Comment by dhanadhan** [comment]
> Sorry, I forgot to update the readme, map to /configs instead of /public. Let me know if you're still having issues after.

Yup, working now. Thank you!
