### ISSUE TITLE
cp: cannot stat '/backup-configs/*':

### ISSUE THREAD

**Issue by mariushosting** [TBosak/mkfd#4]
Docker container logs shows:

cp: cannot stat '/backup-configs/*': No such file or directory

I'm using /configs instead of /public but the issue is always here on a fresh installation

**Comment by TBosak** [comment]
Not indicative of any issues on your end. I was just toying with the idea of leaving some pre-built configs in the image, but decided against it without ever removing the associated script. Went ahead and resolved this in the latest build if you want to pull it down.
